### ISSUE TITLE
"img" directory not found

### ISSUE THREAD

**Issue by radinhamidi** [mttk/STL10#4]
There is an error when we run the code with python 3.6.x. It says there is directory not found which needs us to create the 'img' folder in the current working directory.
I think there is os.mkdir('.\img') needed.

**Comment by pnaszarkowski** [comment]
hi, you run it on linux or windows?

**Comment by radinhamidi** [comment]
@pnaszarkowski Hi
I run it on Windows.

**Comment by pnaszarkowski** [comment]
Issue confirmed  :( fix in progress :)

**Comment by radinhamidi** [comment]
I think you could fix it with the simple code below:

 `
import os
os.mkdir('.\img')
`

**Comment by pnaszarkowski** [comment]
Yes, but I preferred to use method that creates folders recursively. Easy fix.
You can check out: https://github.com/mttk/STL10/pull/5
